### ISSUE TITLE
Seems to initially be copied from my code

### ISSUE THREAD

**Issue by robvdl** [stnc/myPongoGinRender#1]
Original lives on Gitlab https://gitlab.com/go-box/pongo2gin, seems you've copied this code a few times as github.com/stnc/pongo2gin, github.com/stnc/pongo4gin are all copied with the license having my name removed and the git history squashed to hide where it came from.

It credits some others in the README, but all references to me have been removed. That's a bit unfair and seems like claiming work as your own.

Remember the MIT license allows copying, I only ask you give credit to the original author (me) properly and ideally use another name for your library so people don't get confused.

**Comment by stnc** [comment]
I did not know that it was your work, the person I refer to received from you, I am very sorry, I added you https://github.com/stnc/pongo4gin/blob/main/README.md https://github.com/stnc/pongo2gin/blob/master/README.md 22.02.2022, 08:20, "Rob van der Linde" ***@***.***>:
Original lives on Gitlab https://gitlab.com/go-box/pongo2gin, seems you've copied this code a few times as github.com/stnc/pongo2gin, github.com/stnc/pongo4gin are all copied with the license having my name removed and the git history squashed to hide where it came from.
It credits some others in the README, but all references to me have been removed.

**Comment by stnc** [comment]
I did not know that it was your work, the person I refer to received from you, I am very sorry, I added you
 
https://github.com/stnc/pongo4gin/blob/main/README.md
 
https://github.com/stnc/pongo2gin/blob/master/README.md
